# Generated by Django 5.1.4 on 2024-12-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shop_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Order Information",
                "ordering": ["id"],
            },
        ),
    ]
