# Generated by Django 5.1.4 on 2025-01-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product_id",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop_id",
            field=models.CharField(max_length=100),
        ),
    ]
