# Generated by Django 5.1.4 on 2024-12-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stock_pcs",
                    models.IntegerField(
                        default=0, help_text="Enter the number of items in stock."
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vip", models.BooleanField(default=False)),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Information",
                "ordering": ["product_id"],
            },
        ),
    ]
