# Generated by Django 5.1.4 on 2025-01-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_shop_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"], "verbose_name": "Product Information"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
    ]
